directories:
  # The directory containing all of the genomes for the pangenome
  # genome_input_directory: data/genomes

  # A smaller test directory
  # genome_input_directory: data/genomes/test_genomes
  genome_input_directory: data/genomes/all_genomes
  # The directory where all of the intermediate files will be stored
  # (sra prefetch files, fastq dumps, assembly files, etc.)
  # sra_download_directory: /90daydata/fsepru/paul.villanueva/sra_scratch
  # sra_download_directory: output
  working_directory: working

  # Where to store final metrics and genomes
  final_output_directory: output
  # final_metrics_directory: /90daydata/fsepru/paul.villanueva/practice_genomes/metrics
  final_genome_directory: output/genomes
  final_metrics_directory: output/metrics
  plots_directory: output/plots

  # Path to the checkM2 database. Should point to the .dmnd file.



########### Program parameters ############
prokka:

  # The reference pesi genome to annotate the input genomes against
  pesi_reference: /90daydata/fsepru/canderson/infantis/CP052828.gbk


panaroo:

  clean_mode: strict
  core_thresholds: [0.90, 0.95, 0.97, 0.98, 0.99]

metrics:

  # Location of the checkm2 diamond database. It should end in .dmnd. 
  checkm2_database: /project/fsepru/paul.villanueva/databases/CheckM2_database/uniref100.KO.1.dmnd
